name: Create PR from Issue Assignment

on:
  issues:
    types: [assigned]

jobs:
  create-pr-on-assignment:
    runs-on: ubuntu-latest
    if: gitea.event.issue.assignee.login == 'claude'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get issue details
        id: issue
        run: |
          # Install gitea-cli if needed
          if ! command -v tea &> /dev/null; then
            curl -sL https://dl.gitea.io/tea/latest/linux/amd64/tea -o tea
            chmod +x tea
            mv tea /usr/local/bin/
          fi
          
          # Configure tea client
          tea login add -u ${{ vars.GITEA_URL }} --token ${{ secrets.GITEA_TOKEN }}
          
          # Get issue details
          REPO_NAME="${{ gitea.repository }}"
          ISSUE_NUM="${{ gitea.event.issue.number }}"
          
          ISSUE_TITLE=$(tea issue view "$REPO_NAME#$ISSUE_NUM" --format '{{ .Title }}')
          ISSUE_BODY=$(tea issue view "$REPO_NAME#$ISSUE_NUM" --format '{{ .Body }}')
          
          echo "title=$ISSUE_TITLE" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$ISSUE_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        
      - name: Setup Claude Code
        uses: anthropic/claude-code-action@v1
        with:
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
      
      - name: Create branch and changes
        run: |
          # Use issue number for branch name
          BRANCH_NAME="issue-${{ gitea.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          
          # Call Claude Code with issue content as context
          claude-code "Create changes to address this issue: 
          Title: ${{ steps.issue.outputs.title }}
          Description: ${{ steps.issue.outputs.body }}"
      
      - name: Push changes and create PR
        run: |
          git config user.name "Gitea Actions Bot"
          git config user.email "actions-bot@example.com"
          git add .
          git commit -m "Address issue #${{ gitea.event.issue.number }}" || echo "No changes to commit"
          git push origin $BRANCH_NAME          
          # Create PR using tea CLI
          REPO_NAME="${{ gitea.repository }}"
          tea pulls create \
            --repo "$REPO_NAME" \
            --base "main" \
            --head "$BRANCH_NAME" \
            --title "Fix #${{ gitea.event.issue.number }}: ${{ steps.issue.outputs.title }}" \
            --body "This PR addresses issue #${{ gitea.event.issue.number }} \
              Original issue description: \
              ${{ steps.issue.outputs.body }}"          
          # Add a comment on the issue with the PR link
          PR_URL="${{ vars.GITEA_URL }}/$REPO_NAME/pulls/$(tea pulls list --repo "$REPO_NAME" --head "$BRANCH_NAME" --format '{{ .Index }}')"
          tea issue comment "$REPO_NAME#${{ gitea.event.issue.number }}" --body "I've created PR: $PR_URL to address this issue."
          tea issue label "$REPO_NAME#${{ gitea.event.issue.number }}" --add "pr-created"
