name: Create PR from Issue Assignment

on:
  issues:
    types: [assigned]

jobs:
  create-pr-on-assignment:
    runs-on: ubuntu-latest
    if: gitea.event.issue.assignee.login == 'claude'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get issue details
        id: issue
        run: |
          echo "Fetching issue details..."
          echo "Gitea Token: ${{ secrets.GITEA_TOKEN }}"

          # Install gitea-cli if needed
          if ! command -v tea &> /dev/null; then
            echo "Installing gitea-cli..."
            curl -sL https://dl.gitea.io/tea/main/tea-main-linux-amd64 -o tea
            chmod +x tea
            mv tea /usr/local/bin/
          fi
          REPO_NAME="${{ gitea.repository }}"
          echo $REPO_NAME
          ISSUE_NUM="${{ gitea.event.issue.number }}"
          echo $ISSUE_NUM
          tea login add -u https://git.grffn.net/ --token ${{ secrets.GITEA_TOKEN }}
          echo "logged in successfully"
          # tea issue view "$REPO_NAME#$ISSUE_NUM" --format '{{ .Title }}''
          ISSUE_TITLE=$(tea issue --repo $REPO_NAME $ISSUE_NUM --format '{{ .Title }}')
          echo $ISSUE_TITLE
          ISSUE_BODY=$(tea issue --repo $REPO_NAME $ISSUE_NUM)
          echo $ISSUE_BODY
          echo "title=$ISSUE_TITLE" >> $GITHUB_OUTPUT
          # echo "body=<<EOF" >> $GITHUB_OUTPUT
          # echo "$ISSUE_BODY" >> $GITHUB_OUTPUT
          # echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install Claude Code CLI
        run: npm install -g @anthropic-ai/claude-code
      
      - name: Create branch and changes
        run: |
          # Use issue number for branch name
          BRANCH_NAME="issue-${{ gitea.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          git push --set-upstream origin $BRANCH_NAME


          echo "Create changes to address this issue: 
          Title: ${{ steps.issue.outputs.title }} 
          Description: ${{ steps.issue.outputs.body }}"

          # Call Claude Code with issue content as context
          claude  --print "Create changes to address this issue: 
          Title: ${{ steps.issue.outputs.title }} 
          Description: ${{ steps.issue.outputs.body }}"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      
      - name: Push changes and create PR
        run: |
          git config user.name "Gitea Actions Bot"
          git config user.email "actions-bot@example.com"
          git add .
          git commit -m "Address issue #${{ gitea.event.issue.number }}" || echo "No changes to commit"
          git push origin $BRANCH_NAME          
          # Create PR using tea CLI
          REPO_NAME="${{ gitea.repository }}"
          tea pulls create \
            --repo "$REPO_NAME" \
            --base "main" \
            --head "$BRANCH_NAME" \
            --title "Fix #${{ gitea.event.issue.number }}: ${{ steps.issue.outputs.title }}" \
            --body "This PR addresses issue #${{ gitea.event.issue.number }} \
              Original issue description: \
              ${{ steps.issue.outputs.body }}"          
          # Add a comment on the issue with the PR link
          PR_URL="${{ vars.GITEA_URL }}/$REPO_NAME/pulls/$(tea pulls list --repo "$REPO_NAME" --head "$BRANCH_NAME" --format '{{ .Index }}')"
          tea issue comment "$REPO_NAME#${{ gitea.event.issue.number }}" --body "I've created PR: $PR_URL to address this issue."
          tea issue label "$REPO_NAME#${{ gitea.event.issue.number }}" --add "pr-created"