name: Process PR Review on Assignment

on:
  pull_request:
    types: [assigned]

jobs:
  process-pr-on-assignment:
    runs-on: ubuntu-latest
    # Only run when the PR is assigned to the designated bot user
    if: gitea.event.pr.assignee.login == 'claude'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Tea CLI and get PR details
        id: pr
        run: |
          # Install gitea-cli if needed
          if ! command -v tea &> /dev/null; then
            curl -sL https://dl.gitea.io/tea/latest/linux/amd64/tea -o tea
            chmod +x tea
            mv tea /usr/local/bin/
          fi
          
          # Configure tea client
          tea login add -u ${{ vars.GITEA_URL }} --token ${{ secrets.GITEA_TOKEN }}
          
          # Get PR details
          REPO_NAME="${{ gitea.repository }}"
          PR_NUM="${{ gitea.event.pull_request.number }}"
          
          # Get branch name
          PR_BRANCH=$(tea pulls view "$REPO_NAME#$PR_NUM" --format '{{ .Head.Ref }}')
          echo "branch=$PR_BRANCH" >> $GITHUB_OUTPUT
          
          # Get PR comments
          PR_COMMENTS=$(tea pulls comments "$REPO_NAME#$PR_NUM" --format '{{ range . }}{{ .Body }}{{ "\n\n" }}{{ end }}')
          echo "comments<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_COMMENTS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # Get PR review comments
          PR_REVIEW_COMMENTS=$(tea pulls reviews "$REPO_NAME#$PR_NUM" --format '{{ range . }}{{ range .Comments }}{{ .Body }}{{ "\n\n" }}{{ end }}{{ end }}')
          echo "review_comments<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_REVIEW_COMMENTS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Setup Claude Code
        uses: anthropic/claude-code-action@v1
        with:
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
      
      - name: Checkout PR branch
        run: |
          git checkout ${{ steps.pr.outputs.branch }}
      
      - name: Process PR comments with Claude Code
        run: |
          # Combine all comments for context
          ALL_COMMENTS="${{ steps.pr.outputs.review_comments }}

${{ steps.pr.outputs.comments }}"
          
          # Pass the comments to Claude Code to process and make changes
          claude-code "Review the following PR feedback and make the requested changes: $ALL_COMMENTS"
      
      - name: Commit and push changes
        run: |
          git config user.name "Gitea Actions Bot"
          git config user.email "actions-bot@example.com"
          git add .
          git commit -m "Address PR review comments triggered by assignment" || echo "No changes to commit"
          git push origin ${{ steps.pr.outputs.branch }}
      
      - name: Add response comment to PR and unassign
        run: |
          REPO_NAME="${{ gitea.repository }}"
          PR_NUM="${{ gitea.event.pull_request.number }}"
          
          # Add comment to PR
          tea pulls comment "$REPO_NAME#$PR_NUM" --body "I've processed all review comments and made the requested changes. Please review the new commits."
          
          # Unassign the bot to indicate work is complete
          tea pulls edit "$REPO_NAME#$PR_NUM" --unassign ${{ gitea.event.assignee.login }}