name: Test Issue Assignment Trigger
on:
  issues:
    types: [labeled]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print assignee details
        run: echo "Issue assigned event was triggered!"
      - name: Show Assignee Login
        run: echo "Issue was assigned to: ${{ gitea.event.assignee.login }}"
      - name: Dump Assignee Object
        run: echo "Assignee object: ${{ toJson(gitea.event.assignee) }}"
