version: 2
updates:
  # Enable version updates for npm/pnpm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Allow up to 10 open pull requests at a time
    open-pull-requests-limit: 10
    # Set a version update strategy
    versioning-strategy: increase
    # Specify package manager
    package-manager: "npm"
    # Groups to reduce PR noise
    groups:
      # Group all dev dependencies together
      dev-dependencies:
        patterns:
          - "@biomejs/*"
          - "typescript"
          - "vitest"
          - "lefthook"
          - "standard-version"
          - "@changesets/*"
          - "conventional-changelog-cli"
    
  # Also check for updates in each package directory
  - package-ecosystem: "npm"
    directory: "/packages/utils"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    package-manager: "npm"
    
  - package-ecosystem: "npm"
    directory: "/packages/files"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    package-manager: "npm"
    
  - package-ecosystem: "npm"
    directory: "/packages/spider"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    package-manager: "npm"
    
  - package-ecosystem: "npm"
    directory: "/packages/sql"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    package-manager: "npm"
    
  - package-ecosystem: "npm"
    directory: "/packages/pdf"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    package-manager: "npm"
    
  - package-ecosystem: "npm"
    directory: "/packages/ai"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    package-manager: "npm"
    
  - package-ecosystem: "npm"
    directory: "/packages/smrt"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    package-manager: "npm"
    
  - package-ecosystem: "npm"
    directory: "/packages/ocr"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    package-manager: "npm"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    package-manager: "npm"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5