/**
 * Planning workflow comments
 */

import type { IRepository } from '@have/repos';
import { formatDefinitionOfReady } from './definition-of-ready.js';
import type { DefinitionOfReady, ImplementationPlan } from './types.js';

/**
 * Post implementation plan comment
 */
export async function postPlanComment(
  repo: IRepository,
  issueNumber: number,
  plan: ImplementationPlan,
): Promise<void> {
  const comment = `## 🤖 Implementation Plan

### Summary
${plan.summary}

### Tasks
${plan.tasks.map((task, i) => `${i + 1}. ${task}`).join('\n')}

### Complexity
**${plan.complexity.charAt(0).toUpperCase() + plan.complexity.slice(1)}**

### Technical Considerations
${plan.considerations.map((c) => `- ${c}`).join('\n')}

${plan.affected_files && plan.affected_files.length > 0 ? `### Affected Files\n${plan.affected_files.map((f) => `- \`${f}\``).join('\n')}` : ''}

${plan.dependencies && plan.dependencies.length > 0 ? `### Dependencies\n${plan.dependencies.map((d) => `- ${d}`).join('\n')}` : ''}

---
*This plan was generated by AI. Please review and provide feedback in the comments.*`;

  await repo.addComment(issueNumber, comment);
}

/**
 * Post Definition of Ready status comment
 */
export async function postReadyCheckComment(
  repo: IRepository,
  issueNumber: number,
  dor: DefinitionOfReady,
): Promise<void> {
  const comment = formatDefinitionOfReady(dor);
  await repo.addComment(issueNumber, comment);
}

/**
 * Post planning error comment
 */
export async function postPlanningErrorComment(
  repo: IRepository,
  issueNumber: number,
  error: Error,
): Promise<void> {
  const comment = `## ⚠️ Planning Failed

An error occurred while creating the implementation plan:

\`\`\`
${error.message}
\`\`\`

Please try again or create a manual implementation plan in the comments.`;

  await repo.addComment(issueNumber, comment);
}
