name: merged to master

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history.

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Show pnpm version
        run: pnpm --version

      - name: Configure pnpm registry and authentication
        run: |
          pnpm config set @happyvertical:registry=https://git.grffn.net/api/packages/happyvertical/npm/
          pnpm config set @have:registry=https://git.grffn.net/api/packages/happyvertical/npm/
          echo "//git.grffn.net/api/packages/happyvertical/npm/:_authToken=${{ secrets.GITEATOKEN }}" > .npmrc

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright # Default Playwright cache directory.
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Build packages
        run: pnpm build

      - name: Commit and push changes for release
        run: |
          git config user.name "Gitea Bot"
          git config user.email "bot@example.com"

      - name: Bump version and release
        run: pnpm run release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "chore(release): bump version to $(node -p "require('./package.json').version")" --no-verify
          git push --follow-tags

      - name: Publish packages
        run: pnpm run publish-packages
