version: "3.1"
services:
  postgres:
    image: postgres:latest@sha256:4aabea78cf39b90e834caf3af7d602a18565f6fe2508705c8d01aa63245c2e20
    environment:
      POSTGRES_USER: sqloo
      POSTGRES_PASSWORD: sqloo
      POSTGRES_DB: sqloo
    ports:
      - "35432:5432"
