version: "3.1"
services:
  postgres:
    image: postgres:latest@sha256:69e8582b781cb44fa4557b98ed586fe68361e320d9b12f9707494335634f4f3d
    environment:
      POSTGRES_USER: sqloo
      POSTGRES_PASSWORD: sqloo
      POSTGRES_DB: sqloo
    ports:
      - "35432:5432"
