/**
 * ProfileType model - Lookup table defining profile types
 *
 * Represents the nature of a profile (e.g., 'human', 'org', 'robot').
 * Uses UUID primary key with unique slug for human-readable lookups.
 */

import { SmrtObject, type SmrtObjectOptions, smrt } from '@have/smrt';
import { text } from '@have/smrt/fields';

export interface ProfileTypeOptions extends SmrtObjectOptions {
  slug?: string;
  name?: string;
  description?: string;
}

@smrt({
  api: { include: ['list', 'get', 'create', 'update'] },
  mcp: { include: ['list', 'get'] },
  cli: true,
})
export class ProfileType extends SmrtObject {
  // id: UUID (auto-generated by SmrtObject)
  slug = text({ unique: true, required: true }); // Unique slug for lookups
  name = text({ required: true });
  description = text();

  constructor(options: ProfileTypeOptions = {}) {
    super(options);
    if (options.slug) this.slug = options.slug;
    if (options.name) this.name = options.name;
    if (options.description) this.description = options.description;
  }

  /**
   * Convenience method for slug-based lookup
   *
   * @param slug - The slug to search for
   * @returns ProfileType instance or null if not found
   */
  static async getBySlug(slug: string): Promise<ProfileType | null> {
    // Will be auto-implemented by SMRT
    return null;
  }
}
