import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: '@happyvertical/ai',
      link: { type: 'doc', id: 'ai' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/ai#overview' },
        { type: 'link', label: 'Features', href: '/ai#features' },
        { type: 'link', label: 'Installation', href: '/ai#installation' },
        { type: 'link', label: 'Quick Start', href: '/ai#quick-start' },
        {
          type: 'link',
          label: 'Provider-Specific Features',
          href: '/ai#provider-specific-features',
        },
        { type: 'link', label: 'Advanced Usage', href: '/ai#advanced-usage' },
        { type: 'link', label: '📚 API Reference', href: '/api/ai/globals' },
      ],
    },
    {
      type: 'category',
      label: '@happyvertical/cache',
      link: { type: 'doc', id: 'cache' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/cache#overview' },
        { type: 'link', label: 'Key Features', href: '/cache#key-features' },
        { type: 'link', label: 'Installation', href: '/cache#installation' },
        { type: 'link', label: 'Quick Start', href: '/cache#quick-start' },
        { type: 'link', label: 'Usage', href: '/cache#usage' },
        { type: 'link', label: 'Core API', href: '/cache#core-api' },
        { type: 'link', label: '📚 API Reference', href: '/api/cache/globals' },
      ],
    },
    {
      type: 'category',
      label: '@happyvertical/documents',
      link: { type: 'doc', id: 'documents' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/documents#overview' },
        { type: 'link', label: 'Features', href: '/documents#features' },
        {
          type: 'link',
          label: 'Installation',
          href: '/documents#installation',
        },
        { type: 'link', label: 'Quick Start', href: '/documents#quick-start' },
        {
          type: 'link',
          label: 'Usage Examples',
          href: '/documents#usage-examples',
        },
        {
          type: 'link',
          label: 'API Reference',
          href: '/documents#api-reference',
        },
        {
          type: 'link',
          label: '📚 API Reference',
          href: '/api/documents/globals',
        },
      ],
    },
    {
      type: 'category',
      label: '@happyvertical/files',
      link: { type: 'doc', id: 'files' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/files#overview' },
        { type: 'link', label: 'Key Features', href: '/files#key-features' },
        { type: 'link', label: 'Installation', href: '/files#installation' },
        { type: 'link', label: 'Usage', href: '/files#usage' },
        {
          type: 'link',
          label: 'Current Implementation Status',
          href: '/files#current-implementation-status',
        },
        { type: 'link', label: 'Development', href: '/files#development' },
        { type: 'link', label: '📚 API Reference', href: '/api/files/globals' },
      ],
    },
    {
      type: 'category',
      label: '@happyvertical/geo',
      link: { type: 'doc', id: 'geo' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Features', href: '/geo#features' },
        { type: 'link', label: 'Installation', href: '/geo#installation' },
        { type: 'link', label: 'Quick Start', href: '/geo#quick-start' },
        { type: 'link', label: 'API Reference', href: '/geo#api-reference' },
        { type: 'link', label: 'Error Handling', href: '/geo#error-handling' },
        { type: 'link', label: 'Usage Examples', href: '/geo#usage-examples' },
        { type: 'link', label: '📚 API Reference', href: '/api/geo/globals' },
      ],
    },
    {
      type: 'category',
      label: '@happyvertical/logger',
      link: { type: 'doc', id: 'logger' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/logger#overview' },
        { type: 'link', label: 'Key Features', href: '/logger#key-features' },
        { type: 'link', label: 'Installation', href: '/logger#installation' },
        { type: 'link', label: 'Quick Start', href: '/logger#quick-start' },
        { type: 'link', label: 'Usage', href: '/logger#usage' },
        {
          type: 'link',
          label: 'Advanced Usage',
          href: '/logger#advanced-usage',
        },
        {
          type: 'link',
          label: '📚 API Reference',
          href: '/api/logger/globals',
        },
      ],
    },
    {
      type: 'category',
      label: '@happyvertical/sql',
      link: { type: 'doc', id: 'sql' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/sql#overview' },
        { type: 'link', label: 'Features', href: '/sql#features' },
        { type: 'link', label: 'Installation', href: '/sql#installation' },
        { type: 'link', label: 'Usage', href: '/sql#usage' },
        {
          type: 'link',
          label: 'Writing Custom Adapters',
          href: '/sql#writing-custom-adapters',
        },
        {
          type: 'link',
          label: 'Important Notes',
          href: '/sql#important-notes',
        },
        { type: 'link', label: '📚 API Reference', href: '/api/sql/globals' },
      ],
    },
    {
      type: 'category',
      label: '@happyvertical/translator',
      link: { type: 'doc', id: 'translator' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Features', href: '/translator#features' },
        {
          type: 'link',
          label: 'Installation',
          href: '/translator#installation',
        },
        { type: 'link', label: 'Quick Start', href: '/translator#quick-start' },
        {
          type: 'link',
          label: 'Template Function - The Key Feature',
          href: '/translator#template-function---the-key-feature',
        },
        {
          type: 'link',
          label: 'API Reference',
          href: '/translator#api-reference',
        },
        {
          type: 'link',
          label: 'Error Handling',
          href: '/translator#error-handling',
        },
        {
          type: 'link',
          label: '📚 API Reference',
          href: '/api/translator/globals',
        },
      ],
    },
    {
      type: 'category',
      label: '@happyvertical/utils',
      link: { type: 'doc', id: 'utils' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/utils#overview' },
        { type: 'link', label: 'Features', href: '/utils#features' },
        { type: 'link', label: 'Installation', href: '/utils#installation' },
        { type: 'link', label: 'Usage', href: '/utils#usage' },
        { type: 'link', label: 'API Reference', href: '/utils#api-reference' },
        { type: 'link', label: 'Dependencies', href: '/utils#dependencies' },
        { type: 'link', label: '📚 API Reference', href: '/api/utils/globals' },
      ],
    },
    { type: 'doc', id: 'auth', label: '@happyvertical/auth' },
    { type: 'doc', id: 'comfyui', label: '@happyvertical/comfyui' },
    { type: 'doc', id: 'encryption', label: '@happyvertical/encryption' },
    {
      type: 'doc',
      id: 'github-actions',
      label: '@happyvertical/github-actions',
    },
    { type: 'doc', id: 'json', label: '@happyvertical/json' },
    { type: 'doc', id: 'projects', label: '@happyvertical/projects' },
    { type: 'doc', id: 'repos', label: '@happyvertical/repos' },
    { type: 'doc', id: 'sdk-mcp', label: '@happyvertical/sdk-mcp' },
    { type: 'doc', id: 'secrets', label: '@happyvertical/secrets' },
    { type: 'doc', id: 'social', label: '@happyvertical/social' },
    { type: 'doc', id: 'video', label: '@happyvertical/video' },
    { type: 'doc', id: 'weather', label: '@happyvertical/weather' },
    {
      type: 'doc',
      id: 'contributing',
      label: 'Contributing',
    },
    {
      type: 'doc',
      id: 'license',
      label: 'License',
    },
  ],
};

export default sidebars;
