import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: '@have/ai',
      link: { type: 'doc', id: 'ai' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/ai#overview' },
        { type: 'link', label: 'Features', href: '/ai#features' },
        { type: 'link', label: 'Installation', href: '/ai#installation' },
        { type: 'link', label: 'Quick Start', href: '/ai#quick-start' },
        { type: 'link', label: 'Provider-Specific Features', href: '/ai#provider-specific-features' },
        { type: 'link', label: 'Advanced Usage', href: '/ai#advanced-usage' },
        { type: 'link', label: '📚 API Reference', href: '/api/ai/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/cache',
      link: { type: 'doc', id: 'cache' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/cache#overview' },
        { type: 'link', label: 'Key Features', href: '/cache#key-features' },
        { type: 'link', label: 'Installation', href: '/cache#installation' },
        { type: 'link', label: 'Quick Start', href: '/cache#quick-start' },
        { type: 'link', label: 'Usage', href: '/cache#usage' },
        { type: 'link', label: 'Core API', href: '/cache#core-api' },
        { type: 'link', label: '📚 API Reference', href: '/api/cache/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/config',
      link: { type: 'doc', id: 'config' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Features', href: '/config#features' },
        { type: 'link', label: 'Installation', href: '/config#installation' },
        { type: 'link', label: 'Quick Start', href: '/config#quick-start' },
        { type: 'link', label: 'Configuration File Formats', href: '/config#configuration-file-formats' },
        { type: 'link', label: 'API Reference', href: '/config#api-reference' },
        { type: 'link', label: 'Configuration Structure', href: '/config#configuration-structure' },
        { type: 'link', label: '📚 API Reference', href: '/api/config/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/documents',
      link: { type: 'doc', id: 'documents' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/documents#overview' },
        { type: 'link', label: 'Features', href: '/documents#features' },
        { type: 'link', label: 'Installation', href: '/documents#installation' },
        { type: 'link', label: 'Quick Start', href: '/documents#quick-start' },
        { type: 'link', label: 'Usage Examples', href: '/documents#usage-examples' },
        { type: 'link', label: 'API Reference', href: '/documents#api-reference' },
        { type: 'link', label: '📚 API Reference', href: '/api/documents/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/files',
      link: { type: 'doc', id: 'files' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/files#overview' },
        { type: 'link', label: 'Key Features', href: '/files#key-features' },
        { type: 'link', label: 'Installation', href: '/files#installation' },
        { type: 'link', label: 'Usage', href: '/files#usage' },
        { type: 'link', label: 'Current Implementation Status', href: '/files#current-implementation-status' },
        { type: 'link', label: 'Development', href: '/files#development' },
        { type: 'link', label: '📚 API Reference', href: '/api/files/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/geo',
      link: { type: 'doc', id: 'geo' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Features', href: '/geo#features' },
        { type: 'link', label: 'Installation', href: '/geo#installation' },
        { type: 'link', label: 'Quick Start', href: '/geo#quick-start' },
        { type: 'link', label: 'API Reference', href: '/geo#api-reference' },
        { type: 'link', label: 'Error Handling', href: '/geo#error-handling' },
        { type: 'link', label: 'Usage Examples', href: '/geo#usage-examples' },
        { type: 'link', label: '📚 API Reference', href: '/api/geo/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/logger',
      link: { type: 'doc', id: 'logger' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/logger#overview' },
        { type: 'link', label: 'Key Features', href: '/logger#key-features' },
        { type: 'link', label: 'Installation', href: '/logger#installation' },
        { type: 'link', label: 'Quick Start', href: '/logger#quick-start' },
        { type: 'link', label: 'Usage', href: '/logger#usage' },
        { type: 'link', label: 'Advanced Usage', href: '/logger#advanced-usage' },
        { type: 'link', label: '📚 API Reference', href: '/api/logger/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/ocr',
      link: { type: 'doc', id: 'ocr' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/ocr#overview' },
        { type: 'link', label: 'Features', href: '/ocr#features' },
        { type: 'link', label: 'Installation', href: '/ocr#installation' },
        { type: 'link', label: 'Quick Start', href: '/ocr#quick-start' },
        { type: 'link', label: 'Providers', href: '/ocr#providers' },
        { type: 'link', label: 'Advanced Usage', href: '/ocr#advanced-usage' },
        { type: 'link', label: '📚 API Reference', href: '/api/ocr/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/pdf',
      link: { type: 'doc', id: 'pdf' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/pdf#overview' },
        { type: 'link', label: 'Key Features', href: '/pdf#key-features' },
        { type: 'link', label: 'Installation', href: '/pdf#installation' },
        { type: 'link', label: 'Quick Start', href: '/pdf#quick-start' },
        { type: 'link', label: 'Environment Support', href: '/pdf#environment-support' },
        { type: 'link', label: 'Dependencies', href: '/pdf#dependencies' },
        { type: 'link', label: '📚 API Reference', href: '/api/pdf/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/spider',
      link: { type: 'doc', id: 'spider' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/spider#overview' },
        { type: 'link', label: 'Features', href: '/spider#features' },
        { type: 'link', label: 'Installation', href: '/spider#installation' },
        { type: 'link', label: 'Quick Start', href: '/spider#quick-start' },
        { type: 'link', label: 'Adapters', href: '/spider#adapters' },
        { type: 'link', label: 'API Reference', href: '/spider#api-reference' },
        { type: 'link', label: '📚 API Reference', href: '/api/spider/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/sql',
      link: { type: 'doc', id: 'sql' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/sql#overview' },
        { type: 'link', label: 'Features', href: '/sql#features' },
        { type: 'link', label: 'Installation', href: '/sql#installation' },
        { type: 'link', label: 'Usage', href: '/sql#usage' },
        { type: 'link', label: 'Writing Custom Adapters', href: '/sql#writing-custom-adapters' },
        { type: 'link', label: 'Important Notes', href: '/sql#important-notes' },
        { type: 'link', label: '📚 API Reference', href: '/api/sql/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/translator',
      link: { type: 'doc', id: 'translator' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Features', href: '/translator#features' },
        { type: 'link', label: 'Installation', href: '/translator#installation' },
        { type: 'link', label: 'Quick Start', href: '/translator#quick-start' },
        { type: 'link', label: 'Template Function - The Key Feature', href: '/translator#template-function---the-key-feature' },
        { type: 'link', label: 'API Reference', href: '/translator#api-reference' },
        { type: 'link', label: 'Error Handling', href: '/translator#error-handling' },
        { type: 'link', label: '📚 API Reference', href: '/api/translator/globals' },
      ],
    },
    {
      type: 'category',
      label: '@have/utils',
      link: { type: 'doc', id: 'utils' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/utils#overview' },
        { type: 'link', label: 'Features', href: '/utils#features' },
        { type: 'link', label: 'Installation', href: '/utils#installation' },
        { type: 'link', label: 'Usage', href: '/utils#usage' },
        { type: 'link', label: 'API Reference', href: '/utils#api-reference' },
        { type: 'link', label: 'Dependencies', href: '/utils#dependencies' },
        { type: 'link', label: '📚 API Reference', href: '/api/utils/globals' },
      ],
    },
    {
      type: 'doc',
      id: 'contributing',
      label: 'Contributing',
    },
    {
      type: 'doc',
      id: 'license',
      label: 'License',
    },
  ],
};

export default sidebars;
