name: On Merge Main

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (no actual release)'
        required: false
        default: 'false'
        type: boolean

      skip-docs:
        description: 'Skip documentation deployment'
        required: false
        default: 'false'
        type: boolean

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  id-token: write
  pages: write

jobs:
  # Job 1: Run test suite
  test:
    name: Test Suite
    uses: ./.github/workflows/test-suite.yml
    with:
      runner: 'ubuntu-latest'
      node-version: '24'

  # Job 2: Build and release (only if tests pass)
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    needs: [test]
    if: needs.test.outputs.success == 'true'

    outputs:
      version: ${{ steps.semantic-release.outputs.version }}
      published: ${{ steps.semantic-release.outputs.published }}

    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Build packages
        run: pnpm run build

      - name: Release packages
        id: semantic-release
        run: |
          if [ "${{ github.event.inputs.dry-run }}" = "true" ]; then
            echo "Running in dry-run mode..."
            pnpm dlx semantic-release --dry-run
          else
            echo "Running semantic-release..."
            pnpm dlx semantic-release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN not needed since npmPublish is disabled

  # Job 3: Deploy documentation (only if build succeeds and docs changed)
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: [build-and-release]
    if: |
      always() &&
      needs.build-and-release.result == 'success' &&
      github.event.inputs.skip-docs != 'true' &&
      (
        contains(github.event.head_commit.modified, 'docs/') ||
        contains(github.event.head_commit.added, 'docs/') ||
        github.event_name == 'workflow_dispatch'
      )

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: '24'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build documentation site
        run: pnpm run docs:site:build
        env:
          NODE_OPTIONS: --max_old_space_size=8192

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4