name: Test Suite

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/devcontainers/features/base:1

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
          PGUSER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup devcontainer environment
        run: |
          # Install system dependencies for ONNX Runtime and OCR
          apt-get update && apt-get install -y \
            libstdc++6 \
            libc6-dev \
            build-essential \
            gcc \
            g++ \
            cmake \
            libgomp1 \
            libprotobuf-dev \
            git-lfs \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install

      - name: Type check
        run: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run typecheck

      - name: Build packages
        run: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build

      - name: Run tests
        run: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun test
        env:
          SQLOO_HOST: postgres
          SQLOO_USER: postgres
          SQLOO_PASSWORD: postgres
          SQLOO_DATABASE: testdb
          SQLOO_PORT: 5432

