name: Test Suite

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
          PGUSER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install system dependencies for ONNX Runtime
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libstdc++6 \
            libc6-dev \
            build-essential \
            gcc \
            g++ \
            cmake \
            libgomp1 \
            libprotobuf-dev

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          # Force ONNX Runtime to skip CUDA installation
          ONNXRUNTIME_NODE_INSTALL_CUDA: 'skip'

      - name: Build packages
        run: pnpm run build

      - name: Type check
        run: pnpm run typecheck

      - name: Run tests
        run: pnpm test
        env:
          SQLOO_HOST: localhost
          SQLOO_USER: postgres
          SQLOO_PASSWORD: postgres
          SQLOO_DATABASE: testdb
          SQLOO_PORT: 5432

