name: Test Suite

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
          PGUSER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.17"

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: bun run build

      - name: Run tests
        run: bun test --run
        env:
          SQLOO_HOST: localhost
          SQLOO_USER: postgres
          SQLOO_PASSWORD: postgres
          SQLOO_DATABASE: testdb
          SQLOO_PORT: 5432

      - name: Run SQLite tests specifically
        run: bun test packages/sql/src/sqlite.spec.ts

      - name: Run PostgreSQL tests specifically
        run: bun test packages/sql/src/postgres.spec.ts
        env:
          SQLOO_HOST: localhost
          SQLOO_USER: postgres
          SQLOO_PASSWORD: postgres
          SQLOO_DATABASE: testdb
          SQLOO_PORT: 5432